export const companyUsers = [
  {
    id: "usr-101",
    name: "Jane Smith",
    email: "jane@studio.kr",
    company: "Nova FinTech",
    role: "Admin",
    status: "ACTIVE",
    lastActive: "2시간 전",
    joined: "2022-04-10",
    phone: "010-1234-5678",
    avatarUrl: "https://i.pravatar.cc/80?img=47",
    projects: [
      {
        id: "prj-1",
        client: "Aperture Studios",
        title: "웹사이트 리디자인",
        role: "Project Lead",
        owner: "Jane Smith",
        status: "In Progress",
        description: "모던한 디자인으로 회사 웹사이트를 전면 개편",
        manager: "Lena Morris",
        teamSize: "5명",
        tasks: "24건",
        start: "2024년 9월 1일",
        due: "2024년 12월 15일",
        progress: 75,
      },
      {
        id: "prj-2",
        client: "Nova FinTech",
        title: "클라이언트 CRM",
        role: "Product Owner",
        owner: "Jane Smith",
        status: "검토 중",
        description: "CRM 워크플로 업데이트와 신규 자동화 규칙",
        manager: "Ethan Ward",
        teamSize: "4명",
        tasks: "18건",
        start: "2024년 8월 10일",
        due: "2024년 11월 30일",
        progress: 63,
      },
    ],
  },
  {
    id: "usr-102",
    name: "Chris Davis",
    email: "chris@workhub.com",
    company: "WorkHub Labs",
    role: "Developer",
    status: "ACTIVE",
    lastActive: "18분 전",
    joined: "2023-01-18",
    phone: "010-9876-5432",
    avatarUrl: "https://i.pravatar.cc/80?img=12",
    projects: [
      {
        id: "prj-4",
        client: "WorkHub Labs",
        title: "대시보드 V2",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "In Progress",
        description: "분석 위젯과 워크플로 차트 구현",
        manager: "Lena Park",
        teamSize: "7명",
        tasks: "28건",
        start: "2024년 9월 20일",
        due: "2024년 12월 10일",
        progress: 54,
      },
      {
        id: "prj-5",
        client: "Unity Logistics",
        title: "모바일 앱",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "In Progress",
        description: "운전자용 일정 뷰와 알림을 구현",
        manager: "Daniel Cho",
        teamSize: "6명",
        tasks: "26건",
        start: "2024년 8월 5일",
        due: "2024년 11월 25일",
        progress: 71,
      },
      {
        id: "prj-6",
        client: "Atlas Co",
        title: "물류 대시보드",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "Review",
        description: "운송사 분석 화면의 반응형 비주얼 마무리",
        manager: "Michael Green",
        teamSize: "4명",
        tasks: "19건",
        start: "2024년 9월 12일",
        due: "2024년 12월 2일",
        progress: 68,
      },
      {
        id: "prj-7",
        client: "Lumina Labs",
        title: "지식베이스",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "Planning",
        description: "엔터프라이즈 고객을 위한 셀프 서비스 지식베이스 구성",
        manager: "Lena Park",
        teamSize: "3명",
        tasks: "10건",
        start: "2024년 11월 25일",
        due: "2025년 3월 5일",
        progress: 10,
      },
    ],
  },
  {
    id: "usr-103",
    name: "Ava Kim",
    email: "ava@designplus.io",
    company: "DesignPlus",
    role: "Client",
    status: "INACTIVE",
    lastActive: "5일 전",
    joined: "2023-09-05",
    phone: "010-5555-7777",
    avatarUrl: "https://i.pravatar.cc/80?img=32",
    projects: [
      {
        id: "prj-8",
        client: "DesignPlus",
        title: "브랜드 리프레시",
        role: "Stakeholder",
        owner: "Ava Kim",
        status: "Paused",
        description: "브랜드 가이드라인 업데이트 협업",
        manager: "Noah Lee",
        teamSize: "3명",
        tasks: "12건",
        start: "2024년 7월 10일",
        due: "2024년 10월 20일",
        progress: 35,
      },
    ],
  },
  {
    id: "usr-104",
    name: "Noah Lee",
    email: "noah@buildly.dev",
    company: "WorkHub Labs",
    role: "Admin",
    status: "SUSPENDED",
    lastActive: "30일 전",
    joined: "2021-11-02",
    phone: "010-1111-2222",
    avatarUrl: "https://i.pravatar.cc/80?img=21",
    projects: [
      {
        id: "prj-9",
        client: "WorkHub Labs",
        title: "보안 감사",
        role: "Owner",
        owner: "Noah Lee",
        status: "On Hold",
        description: "내부 보안 프로세스 점검",
        manager: "Security Team",
        teamSize: "4명",
        tasks: "15건",
        start: "2024년 5월 1일",
        due: "2024년 9월 1일",
        progress: 20,
      },
    ],
  },
  {
    id: "usr-105",
    name: "Lena Morris",
    email: "lena@aperture.io",
    company: "Aperture Studios",
    role: "Developer",
    status: "ACTIVE",
    lastActive: "1시간 전",
    joined: "2022-08-14",
    phone: "010-3333-5555",
    avatarUrl: "https://i.pravatar.cc/80?img=15",
    projects: [
      {
        id: "prj-10",
        client: "Aperture Studios",
        title: "콘텐츠 허브",
        role: "Lead Dev",
        owner: "Lena Morris",
        status: "In Progress",
        description: "콘텐츠 워크플로 자동화",
        manager: "Jane Smith",
        teamSize: "6명",
        tasks: "22건",
        start: "2024년 6월 1일",
        due: "2024년 12월 1일",
        progress: 58,
      },
    ],
  },
  {
    id: "usr-106",
    name: "Ethan Ward",
    email: "ethan@nova.io",
    company: "Nova FinTech",
    role: "Developer",
    status: "ACTIVE",
    lastActive: "12분 전",
    joined: "2022-10-01",
    phone: "010-4444-6666",
    avatarUrl: "https://i.pravatar.cc/80?img=18",
    projects: [
      {
        id: "prj-11",
        client: "Nova FinTech",
        title: "결제 게이트웨이",
        role: "Backend Lead",
        owner: "Ethan Ward",
        status: "Review",
        description: "결제 보안 컴플라이언스 업데이트",
        manager: "Noah Lee",
        teamSize: "5명",
        tasks: "14건",
        start: "2024년 5월 15일",
        due: "2024년 11월 30일",
        progress: 48,
      },
    ],
  },
  {
    id: "usr-107",
    name: "Nora Lee",
    email: "nora@globemart.com",
    company: "GlobeMart",
    role: "Client",
    status: "INACTIVE",
    lastActive: "15일 전",
    joined: "2023-02-19",
    phone: "010-7777-9999",
    avatarUrl: "https://i.pravatar.cc/80?img=9",
    projects: [],
  },
  {
    id: "usr-108",
    name: "Chris Reynolds",
    email: "chris@unitylogistics.com",
    company: "Unity Logistics",
    role: "Developer",
    status: "ACTIVE",
    lastActive: "3시간 전",
    joined: "2021-05-11",
    phone: "010-1234-8888",
    avatarUrl: "https://i.pravatar.cc/80?img=28",
    projects: [
      {
        id: "prj-12",
        client: "Unity Logistics",
        title: "운송 모니터링",
        role: "Lead Engineer",
        owner: "Chris Reynolds",
        status: "In Progress",
        description: "실시간 운송 대시보드",
        manager: "Daniel Cho",
        teamSize: "8명",
        tasks: "32건",
        start: "2024년 3월 1일",
        due: "2024년 11월 15일",
        progress: 67,
      },
    ],
  },
  {
    id: "usr-109",
    name: "Lena Park",
    email: "lena@lumina.ai",
    company: "Lumina Labs",
    role: "Developer",
    status: "ACTIVE",
    lastActive: "45분 전",
    joined: "2023-03-05",
    phone: "010-2345-8888",
    avatarUrl: "https://i.pravatar.cc/80?img=44",
    projects: [
      {
        id: "prj-13",
        client: "Lumina Labs",
        title: "AI 리포팅",
        role: "UX Dev",
        owner: "Lena Park",
        status: "Planning",
        description: "AI 분석 리포트 UI",
        manager: "Chris Davis",
        teamSize: "4명",
        tasks: "11건",
        start: "2024년 10월 1일",
        due: "2025년 1월 20일",
        progress: 15,
      },
    ],
  },
  {
    id: "usr-110",
    name: "Daniel Cho",
    email: "daniel@bluewave.io",
    company: "BlueWave Data",
    role: "Developer",
    status: "SUSPENDED",
    lastActive: "45일 전",
    joined: "2022-01-23",
    phone: "010-9090-0000",
    avatarUrl: "https://i.pravatar.cc/80?img=36",
    projects: [],
  },
  {
    id: "usr-111",
    name: "Emily Carter",
    email: "emily@stellarhq.com",
    company: "Stellar HQ",
    role: "Client",
    status: "ACTIVE",
    lastActive: "어제",
    joined: "2023-07-17",
    phone: "010-1010-2020",
    avatarUrl: "https://i.pravatar.cc/80?img=53",
    projects: [
      {
        id: "prj-14",
        client: "Stellar HQ",
        title: "온보딩 자동화",
        role: "Stakeholder",
        owner: "Emily Carter",
        status: "In Progress",
        description: "고객 온보딩 자동화 흐름 구축",
        manager: "Jane Smith",
        teamSize: "5명",
        tasks: "20건",
        start: "2024년 8월 1일",
        due: "2024년 12월 30일",
        progress: 46,
      },
    ],
  },
  {
    id: "usr-112",
    name: "Michael Green",
    email: "michael@atlasco.com",
    company: "Atlas Co",
    role: "Client",
    status: "INACTIVE",
    lastActive: "20일 전",
    joined: "2023-09-30",
    phone: "010-3030-4040",
    avatarUrl: "https://i.pravatar.cc/80?img=63",
    projects: [],
  },
];

export const activityHistory = [
  {
    id: 1,
    type: "comment",
    actor: "Jane Smith",
    target: "Nova FinTech · 리디자인",
    message: "대시보드 와이어프레임에 피드백을 남겼습니다",
    timestamp: "오늘 · 08:40",
    updatedAt: "2024-12-02T08:40:00+09:00",
  },
  {
    id: 2,
    type: "upload",
    actor: "Jane Smith",
    target: "Sprint Documents",
    message: "sprint_report_week47.pdf를 업로드했습니다",
    timestamp: "오늘 · 07:55",
    updatedAt: "2024-12-02T07:55:00+09:00",
  },
  {
    id: 3,
    type: "completed",
    actor: "Jane Smith",
    target: "QA Checklist",
    message: "작업 ‘QA 체크리스트’를 완료했습니다",
    timestamp: "어제 · 19:22",
    updatedAt: "2024-12-01T19:22:00+09:00",
  },
  {
    id: 4,
    type: "login",
    actor: "Jane Smith",
    target: "WorkHub",
    message: "SSO로 로그인했습니다",
    timestamp: "어제 · 08:05",
    updatedAt: "2024-12-01T08:05:00+09:00",
  },
  {
    id: 5,
    type: "comment",
    actor: "Jane Smith",
    target: "Stakeholder Update",
    message: "프로젝트 계획을 이해관계자와 공유했습니다",
    timestamp: "어제 · 13:02",
    updatedAt: "2024-12-01T13:02:00+09:00",
  },
  {
    id: 6,
    type: "upload",
    actor: "Jane Smith",
    target: "QA Results",
    message: "QA_results_week48.xlsx를 업로드했습니다",
    timestamp: "11월 20일 · 18:33",
    updatedAt: "2024-11-20T18:33:00+09:00",
  },
  {
    id: 7,
    type: "completed",
    actor: "Jane Smith",
    target: "Sprint 47",
    message: "스프린트 47 회고를 완료했습니다",
    timestamp: "11월 20일 · 16:05",
    updatedAt: "2024-11-20T16:05:00+09:00",
  },
  {
    id: 8,
    type: "comment",
    actor: "Jane Smith",
    target: "API Review",
    message: "백엔드 팀과 API 엔드포인트를 검토했습니다",
    timestamp: "11월 19일 · 10:45",
    updatedAt: "2024-11-19T10:45:00+09:00",
  },
  {
    id: 9,
    type: "upload",
    actor: "Jane Smith",
    target: "Client Feedback",
    message: "client_feedback_round2.docx를 업로드했습니다",
    timestamp: "11월 19일 · 09:15",
    updatedAt: "2024-11-19T09:15:00+09:00",
  },
  {
    id: 10,
    type: "login",
    actor: "Jane Smith",
    target: "WorkHub",
    message: "모바일로 로그인했습니다",
    timestamp: "11월 18일 · 21:04",
    updatedAt: "2024-11-18T21:04:00+09:00",
  },
  {
    id: 11,
    type: "comment",
    actor: "Jane Smith",
    target: "QA Regression",
    message: "QA 회귀 테스트에 메모를 남겼습니다",
    timestamp: "11월 18일 · 18:40",
    updatedAt: "2024-11-18T18:40:00+09:00",
  },
  {
    id: 12,
    type: "upload",
    actor: "Jane Smith",
    target: "Sprint Plan",
    message: "sprint_plan_week49.pdf를 업로드했습니다",
    timestamp: "11월 18일 · 08:23",
    updatedAt: "2024-11-18T08:23:00+09:00",
  },
  {
    id: 13,
    type: "completed",
    actor: "Jane Smith",
    target: "Jira Epic WorkHub-1421",
    message: "지라 에픽 WorkHub-1421을 종료했습니다",
    timestamp: "11월 17일 · 19:10",
    updatedAt: "2024-11-17T19:10:00+09:00",
  },
  {
    id: 14,
    type: "comment",
    actor: "Jane Smith",
    target: "Billing Mockup",
    message: "청구 목업에 코멘트를 추가했습니다",
    timestamp: "11월 17일 · 15:05",
    updatedAt: "2024-11-17T15:05:00+09:00",
  },
  {
    id: 15,
    type: "login",
    actor: "Jane Smith",
    target: "WorkHub",
    message: "데스크톱으로 로그인했습니다",
    timestamp: "11월 17일 · 09:50",
    updatedAt: "2024-11-17T09:50:00+09:00",
  },
  {
    id: 16,
    type: "upload",
    actor: "Jane Smith",
    target: "Design Files",
    message: "onboarding_flow_v4.fig 파일을 업로드했습니다",
    timestamp: "11월 16일 · 22:31",
    updatedAt: "2024-11-16T22:31:00+09:00",
  },
  {
    id: 17,
    type: "comment",
    actor: "Jane Smith",
    target: "Client QA",
    message: "클라이언트 QA 질문에 응답했습니다",
    timestamp: "11월 16일 · 18:45",
    updatedAt: "2024-11-16T18:45:00+09:00",
  },
  {
    id: 18,
    type: "completed",
    actor: "Jane Smith",
    target: "Sprint Grooming",
    message: "스프린트 그루밍 작업을 완료했습니다",
    timestamp: "11월 16일 · 13:27",
    updatedAt: "2024-11-16T13:27:00+09:00",
  },
  {
    id: 19,
    type: "upload",
    actor: "Jane Smith",
    target: "Metrics Dashboard",
    message: "metrics-dashboard.png를 업로드했습니다",
    timestamp: "11월 15일 · 20:14",
    updatedAt: "2024-11-15T20:14:00+09:00",
  },
  {
    id: 20,
    type: "comment",
    actor: "Jane Smith",
    target: "Product Metrics",
    message: "대시보드 지표를 PM과 공유했습니다",
    timestamp: "11월 15일 · 11:03",
    updatedAt: "2024-11-15T11:03:00+09:00",
  },
  {
    id: 21,
    type: "completed",
    actor: "Jane Smith",
    target: "Accessibility Audit",
    message: "접근성 점검을 마쳤습니다",
    timestamp: "11월 14일 · 17:28",
    updatedAt: "2024-11-14T17:28:00+09:00",
  },
  {
    id: 22,
    type: "login",
    actor: "Jane Smith",
    target: "WorkHub",
    message: "태블릿으로 로그인했습니다",
    timestamp: "11월 14일 · 08:40",
    updatedAt: "2024-11-14T08:40:00+09:00",
  },
  {
    id: 23,
    type: "upload",
    actor: "Jane Smith",
    target: "User Testing Notes",
    message: "user_testing_notes.docx를 업로드했습니다",
    timestamp: "11월 13일 · 19:12",
    updatedAt: "2024-11-13T19:12:00+09:00",
  },
  {
    id: 24,
    type: "comment",
    actor: "Jane Smith",
    target: "Bug Backlog",
    message: "QA 팀과 버그 백로그를 점검했습니다",
    timestamp: "11월 13일 · 14:07",
    updatedAt: "2024-11-13T14:07:00+09:00",
  },
];
