export const companyUsers = [
  {
    id: "usr-101",
    name: "Jane Smith",
    email: "jane@studio.kr",
    company: "Nova FinTech",
    role: "Manager",
    status: "Active",
    lastActive: "2시간 전",
    phone: "010-1234-5678",
    avatarUrl: "https://i.pravatar.cc/80?img=47",
    projects: [
      {
        id: "prj-1",
        client: "Aperture Studios",
        title: "웹사이트 리디자인",
        role: "Project Lead",
        owner: "Jane Smith",
        status: "In Progress",
        description: "모던한 디자인으로 회사 웹사이트를 전면 개편",
        manager: "Lena Morris",
        teamSize: "5명",
        tasks: "24건",
        start: "2024년 9월 1일",
        due: "2024년 12월 15일",
        progress: 75,
      },
      {
        id: "prj-2",
        client: "Nova FinTech",
        title: "클라이언트 CRM",
        role: "Product Owner",
        owner: "Jane Smith",
        status: "검토 중",
        description: "CRM 워크플로 업데이트와 신규 자동화 규칙",
        manager: "Ethan Ward",
        teamSize: "4명",
        tasks: "18건",
        start: "2024년 8월 10일",
        due: "2024년 11월 30일",
        progress: 63,
      },
    ],
  },
  {
    id: "usr-102",
    name: "Chris Davis",
    email: "chris@workhub.com",
    company: "WorkHub Labs",
    role: "Developer",
    status: "Active",
    lastActive: "18분 전",
    phone: "010-9876-5432",
    avatarUrl: "https://i.pravatar.cc/80?img=12",
    projects: [
      {
        id: "prj-4",
        client: "WorkHub Labs",
        title: "대시보드 V2",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "In Progress",
        description: "분석 위젯과 워크플로 차트 구현",
        manager: "Lena Park",
        teamSize: "7명",
        tasks: "28건",
        start: "2024년 9월 20일",
        due: "2024년 12월 10일",
        progress: 54,
      },
      {
        id: "prj-5",
        client: "Unity Logistics",
        title: "모바일 앱",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "In Progress",
        description: "운전자용 일정 뷰와 알림을 구현",
        manager: "Daniel Cho",
        teamSize: "6명",
        tasks: "26건",
        start: "2024년 8월 5일",
        due: "2024년 11월 25일",
        progress: 71,
      },
      {
        id: "prj-6",
        client: "Atlas Co",
        title: "물류 대시보드",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "Review",
        description: "운송사 분석 화면의 반응형 비주얼 마무리",
        manager: "Michael Green",
        teamSize: "4명",
        tasks: "19건",
        start: "2024년 9월 12일",
        due: "2024년 12월 2일",
        progress: 68,
      },
      {
        id: "prj-7",
        client: "Lumina Labs",
        title: "지식베이스",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "Planning",
        description: "엔터프라이즈 고객을 위한 셀프 서비스 지식베이스 구성",
        manager: "Lena Park",
        teamSize: "3명",
        tasks: "10건",
        start: "2024년 11월 25일",
        due: "2025년 3월 5일",
        progress: 10,
      },
    ],
  },
];

export const activityHistory = [
  { id: 1, type: "comment", message: "대시보드 와이어프레임에 피드백을 남겼습니다", timestamp: "오늘 · 08:40" },
  { id: 2, type: "upload", message: "sprint_report_week47.pdf를 업로드했습니다", timestamp: "오늘 · 07:55" },
  { id: 3, type: "completed", message: "작업 ‘QA 체크리스트’를 완료했습니다", timestamp: "어제 · 19:22" },
  { id: 4, type: "login", message: "SSO로 로그인했습니다", timestamp: "어제 · 08:05" },
  { id: 5, type: "comment", message: "프로젝트 계획을 이해관계자와 공유했습니다", timestamp: "어제 · 13:02" },
  { id: 6, type: "upload", message: "QA_results_week48.xlsx를 업로드했습니다", timestamp: "11월 20일 · 18:33" },
  { id: 7, type: "completed", message: "스프린트 47 회고를 완료했습니다", timestamp: "11월 20일 · 16:05" },
  { id: 8, type: "comment", message: "백엔드 팀과 API 엔드포인트를 검토했습니다", timestamp: "11월 19일 · 10:45" },
  { id: 9, type: "upload", message: "client_feedback_round2.docx를 업로드했습니다", timestamp: "11월 19일 · 09:15" },
  { id: 10, type: "login", message: "모바일로 로그인했습니다", timestamp: "11월 18일 · 21:04" },
  { id: 11, type: "comment", message: "QA 회귀 테스트에 메모를 남겼습니다", timestamp: "11월 18일 · 18:40" },
  { id: 12, type: "upload", message: "sprint_plan_week49.pdf를 업로드했습니다", timestamp: "11월 18일 · 08:23" },
  { id: 13, type: "completed", message: "지라 에픽 WorkHub-1421을 종료했습니다", timestamp: "11월 17일 · 19:10" },
  { id: 14, type: "comment", message: "청구 목업에 코멘트를 추가했습니다", timestamp: "11월 17일 · 15:05" },
  { id: 15, type: "login", message: "데스크톱으로 로그인했습니다", timestamp: "11월 17일 · 09:50" },
  { id: 16, type: "upload", message: "onboarding_flow_v4.fig 파일을 업로드했습니다", timestamp: "11월 16일 · 22:31" },
  { id: 17, type: "comment", message: "클라이언트 QA 질문에 응답했습니다", timestamp: "11월 16일 · 18:45" },
  { id: 18, type: "completed", message: "스프린트 그루밍 작업을 완료했습니다", timestamp: "11월 16일 · 13:27" },
  { id: 19, type: "upload", message: "metrics-dashboard.png를 업로드했습니다", timestamp: "11월 15일 · 20:14" },
  { id: 20, type: "comment", message: "대시보드 지표를 PM과 공유했습니다", timestamp: "11월 15일 · 11:03" },
  { id: 21, type: "completed", message: "접근성 점검을 마쳤습니다", timestamp: "11월 14일 · 17:28" },
  { id: 22, type: "login", message: "태블릿으로 로그인했습니다", timestamp: "11월 14일 · 08:40" },
  { id: 23, type: "upload", message: "user_testing_notes.docx를 업로드했습니다", timestamp: "11월 13일 · 19:12" },
  { id: 24, type: "comment", message: "QA 팀과 버그 백로그를 점검했습니다", timestamp: "11월 13일 · 14:07" },
];
