export const companyUsers = [
  {
    id: "usr-101",
    name: "Jane Smith",
    email: "jane@studio.kr",
    company: "Nova FinTech",
    role: "Manager",
    status: "Active",
    lastActive: "2 hours ago",
    phone: "010-1234-5678",
    avatarUrl: "https://i.pravatar.cc/80?img=47",
    projects: [
      {
        id: "prj-1",
        client: "Aperture Studios",
        title: "Website Redesign",
        role: "Project Lead",
        owner: "Jane Smith",
        status: "In Progress",
        description: "Complete overhaul of company website with modern design",
        manager: "Lena Morris",
        teamSize: "5 members",
        tasks: "24 tasks",
        start: "Sep 01, 2024",
        due: "Dec 15, 2024",
        progress: 75,
      },
      {
        id: "prj-2",
        client: "Nova FinTech",
        title: "Client CRM",
        role: "Product Owner",
        owner: "Jane Smith",
        status: "In Review",
        description: "CRM workflow updates and new automation rules",
        manager: "Ethan Ward",
        teamSize: "4 members",
        tasks: "18 tasks",
        start: "Aug 10, 2024",
        due: "Nov 30, 2024",
        progress: 63,
      },
    ],
  },
  {
    id: "usr-102",
    name: "Chris Davis",
    email: "chris@workhub.com",
    company: "WorkHub Labs",
    role: "Developer",
    status: "Active",
    lastActive: "18 minutes ago",
    phone: "010-9876-5432",
    avatarUrl: "https://i.pravatar.cc/80?img=12",
    projects: [
      {
        id: "prj-4",
        client: "WorkHub Labs",
        title: "Dashboard V2",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "In Progress",
        description: "Implement analytics widgets and workflow charts",
        manager: "Lena Park",
        teamSize: "7 members",
        tasks: "28 tasks",
        start: "Sep 20, 2024",
        due: "Dec 10, 2024",
        progress: 54,
      },
      {
        id: "prj-5",
        client: "Unity Logistics",
        title: "Mobile App",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "In Progress",
        description: "Build schedule view and notifications for drivers",
        manager: "Daniel Cho",
        teamSize: "6 members",
        tasks: "26 tasks",
        start: "Aug 05, 2024",
        due: "Nov 25, 2024",
        progress: 71,
      },
      {
        id: "prj-6",
        client: "Atlas Co",
        title: "Logistics Dashboard",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "Review",
        description: "Finalize responsive visuals for carrier analytics view",
        manager: "Michael Green",
        teamSize: "4 members",
        tasks: "19 tasks",
        start: "Sep 12, 2024",
        due: "Dec 02, 2024",
        progress: 68,
      },
      {
        id: "prj-7",
        client: "Lumina Labs",
        title: "Knowledge Base",
        role: "Frontend Lead",
        owner: "Chris Davis",
        status: "Planning",
        description: "Build self-serve knowledge base for enterprise clients",
        manager: "Lena Park",
        teamSize: "3 members",
        tasks: "10 tasks",
        start: "Nov 25, 2024",
        due: "Mar 05, 2025",
        progress: 10,
      },
    ],
  },
];

export const activityHistory = [
  { id: 1, type: "comment", message: "Left feedback on Dashboard wireframe", timestamp: "Today · 08:40" },
  { id: 2, type: "upload", message: "Uploaded sprint_report_week47.pdf", timestamp: "Today · 07:55" },
  { id: 3, type: "completed", message: "Completed task ‘QA checklist’", timestamp: "Yesterday · 19:22" },
  { id: 4, type: "login", message: "Logged in via SSO", timestamp: "Yesterday · 08:05" },
  { id: 5, type: "comment", message: "Shared project plan with stakeholders", timestamp: "Yesterday · 13:02" },
  { id: 6, type: "upload", message: "Uploaded QA_results_week48.xlsx", timestamp: "Nov 20 · 18:33" },
  { id: 7, type: "completed", message: "Completed Sprint 47 retrospective", timestamp: "Nov 20 · 16:05" },
  { id: 8, type: "comment", message: "Reviewed API endpoints with backend team", timestamp: "Nov 19 · 10:45" },
  { id: 9, type: "upload", message: "Uploaded client_feedback_round2.docx", timestamp: "Nov 19 · 09:15" },
  { id: 10, type: "login", message: "Logged in via mobile", timestamp: "Nov 18 · 21:04" },
  { id: 11, type: "comment", message: "Left note on QA regression tests", timestamp: "Nov 18 · 18:40" },
  { id: 12, type: "upload", message: "Uploaded sprint_plan_week49.pdf", timestamp: "Nov 18 · 08:23" },
  { id: 13, type: "completed", message: "Closed Jira epic WorkHub-1421", timestamp: "Nov 17 · 19:10" },
  { id: 14, type: "comment", message: "Added comments to billing mockups", timestamp: "Nov 17 · 15:05" },
  { id: 15, type: "login", message: "Logged in via desktop", timestamp: "Nov 17 · 09:50" },
  { id: 16, type: "upload", message: "Uploaded onboarding_flow_v4.fig", timestamp: "Nov 16 · 22:31" },
  { id: 17, type: "comment", message: "Responded to client QA questions", timestamp: "Nov 16 · 18:45" },
  { id: 18, type: "completed", message: "Completed sprint grooming tasks", timestamp: "Nov 16 · 13:27" },
  { id: 19, type: "upload", message: "Uploaded metrics-dashboard.png", timestamp: "Nov 15 · 20:14" },
  { id: 20, type: "comment", message: "Shared dashboard metrics with PM", timestamp: "Nov 15 · 11:03" },
  { id: 21, type: "completed", message: "Finished accessibility audit", timestamp: "Nov 14 · 17:28" },
  { id: 22, type: "login", message: "Logged in via tablet", timestamp: "Nov 14 · 08:40" },
  { id: 23, type: "upload", message: "Uploaded user_testing_notes.docx", timestamp: "Nov 13 · 19:12" },
  { id: 24, type: "comment", message: "Checked in with QA on bug backlog", timestamp: "Nov 13 · 14:07" },
];
